export const ROUTES = {
	ABOUT: '/about',
	CONTACTS: '/contacts',
	ADMIN: '/admin',
	LOGIN: '/login',
	REGISTER: '/register',
	HOME: '/',
	CART: '/cart',
	CATALOG: '/catalog',
	CATALOG_CATEGORY: '/catalog/:category',
	WISHLIST: '/wishlist',
	PROFILE: '/profile',
	USERS: '/users',
	PRODUCT: '/products/:productId',
	NOT_FOUND: '*',
	ERROR: '*',
}