export const ROUTES = {
	ABOUT: '/about',
	CONTACTS: '/contacts',
	ADMIN: '/admin',
	LOGIN: '/login',
	REGISTER: '/register',
	HOME: '/',
	CART: '/cart',
	PRODUCTS: '/products',
	PRODUCT: '/products/details/:productId',
	PRODUCT_LINE: '/products/:line',
	PRODUCT_CATEGORY: '/products/category/:category',
	WISHLIST: '/wishlist',
	PROFILE: '/profile',
	USERS: '/users',
	NOT_FOUND: '*',
	ERROR: '*',
}