export const ROUTES = {
	ABOUT: '/about',
	ADMIN: '/admin',
	LOGIN: '/login',
	REGISTER: '/register',
	HOME: '/',
	CART: '/cart',
	ORDER: '/profile/orders/:id',
	ORDERS: '/profile/orders',
	PRODUCT: '/products/details/:productId',
	PRODUCT_LINE: '/products/:line',
	PRODUCT_CATEGORY: '/products/category/:category',
	PROFILE: '/profile',
	WISHLIST: '/wishlist',
	NOT_FOUND: '*',
	ERROR: '*',
};
