export * from './404/NotFound.jsx';
export * from './about/About.jsx';
export * from './authorization/Authorization.jsx';
export * from './cart/Cart';
export * from './home/Home.jsx';
export * from './registration/Registration.jsx';
export * from './products/Products.jsx';
export * from './product/Product.tsx';
export * from './profile/Profile.jsx';
export * from './wishlist/Wishlist.jsx'
